// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/node.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fnode_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fnode_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fnode_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fnode_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fnode_2eproto;
namespace ratelimit {
class LimitRequest;
struct LimitRequestDefaultTypeInternal;
extern LimitRequestDefaultTypeInternal _LimitRequest_default_instance_;
class LimitResponse;
struct LimitResponseDefaultTypeInternal;
extern LimitResponseDefaultTypeInternal _LimitResponse_default_instance_;
class LimitState;
struct LimitStateDefaultTypeInternal;
extern LimitStateDefaultTypeInternal _LimitState_default_instance_;
class SyncState;
struct SyncStateDefaultTypeInternal;
extern SyncStateDefaultTypeInternal _SyncState_default_instance_;
}  // namespace ratelimit
PROTOBUF_NAMESPACE_OPEN
template<> ::ratelimit::LimitRequest* Arena::CreateMaybeMessage<::ratelimit::LimitRequest>(Arena*);
template<> ::ratelimit::LimitResponse* Arena::CreateMaybeMessage<::ratelimit::LimitResponse>(Arena*);
template<> ::ratelimit::LimitState* Arena::CreateMaybeMessage<::ratelimit::LimitState>(Arena*);
template<> ::ratelimit::SyncState* Arena::CreateMaybeMessage<::ratelimit::SyncState>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ratelimit {

// ===================================================================

class LimitState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ratelimit.LimitState) */ {
 public:
  inline LimitState() : LimitState(nullptr) {}
  ~LimitState() override;
  explicit PROTOBUF_CONSTEXPR LimitState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LimitState(const LimitState& from);
  LimitState(LimitState&& from) noexcept
    : LimitState() {
    *this = ::std::move(from);
  }

  inline LimitState& operator=(const LimitState& from) {
    CopyFrom(from);
    return *this;
  }
  inline LimitState& operator=(LimitState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LimitState& default_instance() {
    return *internal_default_instance();
  }
  static inline const LimitState* internal_default_instance() {
    return reinterpret_cast<const LimitState*>(
               &_LimitState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LimitState& a, LimitState& b) {
    a.Swap(&b);
  }
  inline void Swap(LimitState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LimitState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LimitState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LimitState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LimitState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LimitState& from) {
    LimitState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LimitState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ratelimit.LimitState";
  }
  protected:
  explicit LimitState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIdFieldNumber = 1,
    kTokensFieldNumber = 2,
    kLastRefillTimestampFieldNumber = 3,
    kCapacityFieldNumber = 4,
    kRefillRateFieldNumber = 5,
  };
  // string client_id = 1;
  void clear_client_id();
  const std::string& client_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_client_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_client_id();
  PROTOBUF_NODISCARD std::string* release_client_id();
  void set_allocated_client_id(std::string* client_id);
  private:
  const std::string& _internal_client_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_client_id(const std::string& value);
  std::string* _internal_mutable_client_id();
  public:

  // int64 tokens = 2;
  void clear_tokens();
  int64_t tokens() const;
  void set_tokens(int64_t value);
  private:
  int64_t _internal_tokens() const;
  void _internal_set_tokens(int64_t value);
  public:

  // int64 last_refill_timestamp = 3;
  void clear_last_refill_timestamp();
  int64_t last_refill_timestamp() const;
  void set_last_refill_timestamp(int64_t value);
  private:
  int64_t _internal_last_refill_timestamp() const;
  void _internal_set_last_refill_timestamp(int64_t value);
  public:

  // int64 capacity = 4;
  void clear_capacity();
  int64_t capacity() const;
  void set_capacity(int64_t value);
  private:
  int64_t _internal_capacity() const;
  void _internal_set_capacity(int64_t value);
  public:

  // double refill_rate = 5;
  void clear_refill_rate();
  double refill_rate() const;
  void set_refill_rate(double value);
  private:
  double _internal_refill_rate() const;
  void _internal_set_refill_rate(double value);
  public:

  // @@protoc_insertion_point(class_scope:ratelimit.LimitState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr client_id_;
    int64_t tokens_;
    int64_t last_refill_timestamp_;
    int64_t capacity_;
    double refill_rate_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fnode_2eproto;
};
// -------------------------------------------------------------------

class LimitRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ratelimit.LimitRequest) */ {
 public:
  inline LimitRequest() : LimitRequest(nullptr) {}
  ~LimitRequest() override;
  explicit PROTOBUF_CONSTEXPR LimitRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LimitRequest(const LimitRequest& from);
  LimitRequest(LimitRequest&& from) noexcept
    : LimitRequest() {
    *this = ::std::move(from);
  }

  inline LimitRequest& operator=(const LimitRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LimitRequest& operator=(LimitRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LimitRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const LimitRequest* internal_default_instance() {
    return reinterpret_cast<const LimitRequest*>(
               &_LimitRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LimitRequest& a, LimitRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(LimitRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LimitRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LimitRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LimitRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LimitRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LimitRequest& from) {
    LimitRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LimitRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ratelimit.LimitRequest";
  }
  protected:
  explicit LimitRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIdFieldNumber = 1,
    kTokensRequestedFieldNumber = 2,
    kTimestampFieldNumber = 3,
  };
  // string client_id = 1;
  void clear_client_id();
  const std::string& client_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_client_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_client_id();
  PROTOBUF_NODISCARD std::string* release_client_id();
  void set_allocated_client_id(std::string* client_id);
  private:
  const std::string& _internal_client_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_client_id(const std::string& value);
  std::string* _internal_mutable_client_id();
  public:

  // int64 tokens_requested = 2;
  void clear_tokens_requested();
  int64_t tokens_requested() const;
  void set_tokens_requested(int64_t value);
  private:
  int64_t _internal_tokens_requested() const;
  void _internal_set_tokens_requested(int64_t value);
  public:

  // int64 timestamp = 3;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:ratelimit.LimitRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr client_id_;
    int64_t tokens_requested_;
    int64_t timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fnode_2eproto;
};
// -------------------------------------------------------------------

class LimitResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ratelimit.LimitResponse) */ {
 public:
  inline LimitResponse() : LimitResponse(nullptr) {}
  ~LimitResponse() override;
  explicit PROTOBUF_CONSTEXPR LimitResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LimitResponse(const LimitResponse& from);
  LimitResponse(LimitResponse&& from) noexcept
    : LimitResponse() {
    *this = ::std::move(from);
  }

  inline LimitResponse& operator=(const LimitResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline LimitResponse& operator=(LimitResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LimitResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const LimitResponse* internal_default_instance() {
    return reinterpret_cast<const LimitResponse*>(
               &_LimitResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(LimitResponse& a, LimitResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(LimitResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LimitResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LimitResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LimitResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LimitResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LimitResponse& from) {
    LimitResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LimitResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ratelimit.LimitResponse";
  }
  protected:
  explicit LimitResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeIdFieldNumber = 4,
    kRemainingTokensFieldNumber = 2,
    kRetryAfterMsFieldNumber = 3,
    kAllowedFieldNumber = 1,
  };
  // string node_id = 4;
  void clear_node_id();
  const std::string& node_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_node_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_node_id();
  PROTOBUF_NODISCARD std::string* release_node_id();
  void set_allocated_node_id(std::string* node_id);
  private:
  const std::string& _internal_node_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_node_id(const std::string& value);
  std::string* _internal_mutable_node_id();
  public:

  // int64 remaining_tokens = 2;
  void clear_remaining_tokens();
  int64_t remaining_tokens() const;
  void set_remaining_tokens(int64_t value);
  private:
  int64_t _internal_remaining_tokens() const;
  void _internal_set_remaining_tokens(int64_t value);
  public:

  // int64 retry_after_ms = 3;
  void clear_retry_after_ms();
  int64_t retry_after_ms() const;
  void set_retry_after_ms(int64_t value);
  private:
  int64_t _internal_retry_after_ms() const;
  void _internal_set_retry_after_ms(int64_t value);
  public:

  // bool allowed = 1;
  void clear_allowed();
  bool allowed() const;
  void set_allowed(bool value);
  private:
  bool _internal_allowed() const;
  void _internal_set_allowed(bool value);
  public:

  // @@protoc_insertion_point(class_scope:ratelimit.LimitResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr node_id_;
    int64_t remaining_tokens_;
    int64_t retry_after_ms_;
    bool allowed_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fnode_2eproto;
};
// -------------------------------------------------------------------

class SyncState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ratelimit.SyncState) */ {
 public:
  inline SyncState() : SyncState(nullptr) {}
  ~SyncState() override;
  explicit PROTOBUF_CONSTEXPR SyncState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SyncState(const SyncState& from);
  SyncState(SyncState&& from) noexcept
    : SyncState() {
    *this = ::std::move(from);
  }

  inline SyncState& operator=(const SyncState& from) {
    CopyFrom(from);
    return *this;
  }
  inline SyncState& operator=(SyncState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SyncState& default_instance() {
    return *internal_default_instance();
  }
  static inline const SyncState* internal_default_instance() {
    return reinterpret_cast<const SyncState*>(
               &_SyncState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SyncState& a, SyncState& b) {
    a.Swap(&b);
  }
  inline void Swap(SyncState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SyncState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SyncState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SyncState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SyncState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SyncState& from) {
    SyncState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SyncState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ratelimit.SyncState";
  }
  protected:
  explicit SyncState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIdFieldNumber = 1,
    kSourceNodeIdFieldNumber = 4,
    kTokensFieldNumber = 2,
    kLastRefillTimestampFieldNumber = 3,
  };
  // string client_id = 1;
  void clear_client_id();
  const std::string& client_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_client_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_client_id();
  PROTOBUF_NODISCARD std::string* release_client_id();
  void set_allocated_client_id(std::string* client_id);
  private:
  const std::string& _internal_client_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_client_id(const std::string& value);
  std::string* _internal_mutable_client_id();
  public:

  // string source_node_id = 4;
  void clear_source_node_id();
  const std::string& source_node_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_source_node_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_source_node_id();
  PROTOBUF_NODISCARD std::string* release_source_node_id();
  void set_allocated_source_node_id(std::string* source_node_id);
  private:
  const std::string& _internal_source_node_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_source_node_id(const std::string& value);
  std::string* _internal_mutable_source_node_id();
  public:

  // int64 tokens = 2;
  void clear_tokens();
  int64_t tokens() const;
  void set_tokens(int64_t value);
  private:
  int64_t _internal_tokens() const;
  void _internal_set_tokens(int64_t value);
  public:

  // int64 last_refill_timestamp = 3;
  void clear_last_refill_timestamp();
  int64_t last_refill_timestamp() const;
  void set_last_refill_timestamp(int64_t value);
  private:
  int64_t _internal_last_refill_timestamp() const;
  void _internal_set_last_refill_timestamp(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:ratelimit.SyncState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr client_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr source_node_id_;
    int64_t tokens_;
    int64_t last_refill_timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fnode_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LimitState

// string client_id = 1;
inline void LimitState::clear_client_id() {
  _impl_.client_id_.ClearToEmpty();
}
inline const std::string& LimitState::client_id() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitState.client_id)
  return _internal_client_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LimitState::set_client_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.client_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ratelimit.LimitState.client_id)
}
inline std::string* LimitState::mutable_client_id() {
  std::string* _s = _internal_mutable_client_id();
  // @@protoc_insertion_point(field_mutable:ratelimit.LimitState.client_id)
  return _s;
}
inline const std::string& LimitState::_internal_client_id() const {
  return _impl_.client_id_.Get();
}
inline void LimitState::_internal_set_client_id(const std::string& value) {
  
  _impl_.client_id_.Set(value, GetArenaForAllocation());
}
inline std::string* LimitState::_internal_mutable_client_id() {
  
  return _impl_.client_id_.Mutable(GetArenaForAllocation());
}
inline std::string* LimitState::release_client_id() {
  // @@protoc_insertion_point(field_release:ratelimit.LimitState.client_id)
  return _impl_.client_id_.Release();
}
inline void LimitState::set_allocated_client_id(std::string* client_id) {
  if (client_id != nullptr) {
    
  } else {
    
  }
  _impl_.client_id_.SetAllocated(client_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.client_id_.IsDefault()) {
    _impl_.client_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ratelimit.LimitState.client_id)
}

// int64 tokens = 2;
inline void LimitState::clear_tokens() {
  _impl_.tokens_ = int64_t{0};
}
inline int64_t LimitState::_internal_tokens() const {
  return _impl_.tokens_;
}
inline int64_t LimitState::tokens() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitState.tokens)
  return _internal_tokens();
}
inline void LimitState::_internal_set_tokens(int64_t value) {
  
  _impl_.tokens_ = value;
}
inline void LimitState::set_tokens(int64_t value) {
  _internal_set_tokens(value);
  // @@protoc_insertion_point(field_set:ratelimit.LimitState.tokens)
}

// int64 last_refill_timestamp = 3;
inline void LimitState::clear_last_refill_timestamp() {
  _impl_.last_refill_timestamp_ = int64_t{0};
}
inline int64_t LimitState::_internal_last_refill_timestamp() const {
  return _impl_.last_refill_timestamp_;
}
inline int64_t LimitState::last_refill_timestamp() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitState.last_refill_timestamp)
  return _internal_last_refill_timestamp();
}
inline void LimitState::_internal_set_last_refill_timestamp(int64_t value) {
  
  _impl_.last_refill_timestamp_ = value;
}
inline void LimitState::set_last_refill_timestamp(int64_t value) {
  _internal_set_last_refill_timestamp(value);
  // @@protoc_insertion_point(field_set:ratelimit.LimitState.last_refill_timestamp)
}

// int64 capacity = 4;
inline void LimitState::clear_capacity() {
  _impl_.capacity_ = int64_t{0};
}
inline int64_t LimitState::_internal_capacity() const {
  return _impl_.capacity_;
}
inline int64_t LimitState::capacity() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitState.capacity)
  return _internal_capacity();
}
inline void LimitState::_internal_set_capacity(int64_t value) {
  
  _impl_.capacity_ = value;
}
inline void LimitState::set_capacity(int64_t value) {
  _internal_set_capacity(value);
  // @@protoc_insertion_point(field_set:ratelimit.LimitState.capacity)
}

// double refill_rate = 5;
inline void LimitState::clear_refill_rate() {
  _impl_.refill_rate_ = 0;
}
inline double LimitState::_internal_refill_rate() const {
  return _impl_.refill_rate_;
}
inline double LimitState::refill_rate() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitState.refill_rate)
  return _internal_refill_rate();
}
inline void LimitState::_internal_set_refill_rate(double value) {
  
  _impl_.refill_rate_ = value;
}
inline void LimitState::set_refill_rate(double value) {
  _internal_set_refill_rate(value);
  // @@protoc_insertion_point(field_set:ratelimit.LimitState.refill_rate)
}

// -------------------------------------------------------------------

// LimitRequest

// string client_id = 1;
inline void LimitRequest::clear_client_id() {
  _impl_.client_id_.ClearToEmpty();
}
inline const std::string& LimitRequest::client_id() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitRequest.client_id)
  return _internal_client_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LimitRequest::set_client_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.client_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ratelimit.LimitRequest.client_id)
}
inline std::string* LimitRequest::mutable_client_id() {
  std::string* _s = _internal_mutable_client_id();
  // @@protoc_insertion_point(field_mutable:ratelimit.LimitRequest.client_id)
  return _s;
}
inline const std::string& LimitRequest::_internal_client_id() const {
  return _impl_.client_id_.Get();
}
inline void LimitRequest::_internal_set_client_id(const std::string& value) {
  
  _impl_.client_id_.Set(value, GetArenaForAllocation());
}
inline std::string* LimitRequest::_internal_mutable_client_id() {
  
  return _impl_.client_id_.Mutable(GetArenaForAllocation());
}
inline std::string* LimitRequest::release_client_id() {
  // @@protoc_insertion_point(field_release:ratelimit.LimitRequest.client_id)
  return _impl_.client_id_.Release();
}
inline void LimitRequest::set_allocated_client_id(std::string* client_id) {
  if (client_id != nullptr) {
    
  } else {
    
  }
  _impl_.client_id_.SetAllocated(client_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.client_id_.IsDefault()) {
    _impl_.client_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ratelimit.LimitRequest.client_id)
}

// int64 tokens_requested = 2;
inline void LimitRequest::clear_tokens_requested() {
  _impl_.tokens_requested_ = int64_t{0};
}
inline int64_t LimitRequest::_internal_tokens_requested() const {
  return _impl_.tokens_requested_;
}
inline int64_t LimitRequest::tokens_requested() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitRequest.tokens_requested)
  return _internal_tokens_requested();
}
inline void LimitRequest::_internal_set_tokens_requested(int64_t value) {
  
  _impl_.tokens_requested_ = value;
}
inline void LimitRequest::set_tokens_requested(int64_t value) {
  _internal_set_tokens_requested(value);
  // @@protoc_insertion_point(field_set:ratelimit.LimitRequest.tokens_requested)
}

// int64 timestamp = 3;
inline void LimitRequest::clear_timestamp() {
  _impl_.timestamp_ = int64_t{0};
}
inline int64_t LimitRequest::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline int64_t LimitRequest::timestamp() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitRequest.timestamp)
  return _internal_timestamp();
}
inline void LimitRequest::_internal_set_timestamp(int64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void LimitRequest::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:ratelimit.LimitRequest.timestamp)
}

// -------------------------------------------------------------------

// LimitResponse

// bool allowed = 1;
inline void LimitResponse::clear_allowed() {
  _impl_.allowed_ = false;
}
inline bool LimitResponse::_internal_allowed() const {
  return _impl_.allowed_;
}
inline bool LimitResponse::allowed() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitResponse.allowed)
  return _internal_allowed();
}
inline void LimitResponse::_internal_set_allowed(bool value) {
  
  _impl_.allowed_ = value;
}
inline void LimitResponse::set_allowed(bool value) {
  _internal_set_allowed(value);
  // @@protoc_insertion_point(field_set:ratelimit.LimitResponse.allowed)
}

// int64 remaining_tokens = 2;
inline void LimitResponse::clear_remaining_tokens() {
  _impl_.remaining_tokens_ = int64_t{0};
}
inline int64_t LimitResponse::_internal_remaining_tokens() const {
  return _impl_.remaining_tokens_;
}
inline int64_t LimitResponse::remaining_tokens() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitResponse.remaining_tokens)
  return _internal_remaining_tokens();
}
inline void LimitResponse::_internal_set_remaining_tokens(int64_t value) {
  
  _impl_.remaining_tokens_ = value;
}
inline void LimitResponse::set_remaining_tokens(int64_t value) {
  _internal_set_remaining_tokens(value);
  // @@protoc_insertion_point(field_set:ratelimit.LimitResponse.remaining_tokens)
}

// int64 retry_after_ms = 3;
inline void LimitResponse::clear_retry_after_ms() {
  _impl_.retry_after_ms_ = int64_t{0};
}
inline int64_t LimitResponse::_internal_retry_after_ms() const {
  return _impl_.retry_after_ms_;
}
inline int64_t LimitResponse::retry_after_ms() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitResponse.retry_after_ms)
  return _internal_retry_after_ms();
}
inline void LimitResponse::_internal_set_retry_after_ms(int64_t value) {
  
  _impl_.retry_after_ms_ = value;
}
inline void LimitResponse::set_retry_after_ms(int64_t value) {
  _internal_set_retry_after_ms(value);
  // @@protoc_insertion_point(field_set:ratelimit.LimitResponse.retry_after_ms)
}

// string node_id = 4;
inline void LimitResponse::clear_node_id() {
  _impl_.node_id_.ClearToEmpty();
}
inline const std::string& LimitResponse::node_id() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitResponse.node_id)
  return _internal_node_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LimitResponse::set_node_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.node_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ratelimit.LimitResponse.node_id)
}
inline std::string* LimitResponse::mutable_node_id() {
  std::string* _s = _internal_mutable_node_id();
  // @@protoc_insertion_point(field_mutable:ratelimit.LimitResponse.node_id)
  return _s;
}
inline const std::string& LimitResponse::_internal_node_id() const {
  return _impl_.node_id_.Get();
}
inline void LimitResponse::_internal_set_node_id(const std::string& value) {
  
  _impl_.node_id_.Set(value, GetArenaForAllocation());
}
inline std::string* LimitResponse::_internal_mutable_node_id() {
  
  return _impl_.node_id_.Mutable(GetArenaForAllocation());
}
inline std::string* LimitResponse::release_node_id() {
  // @@protoc_insertion_point(field_release:ratelimit.LimitResponse.node_id)
  return _impl_.node_id_.Release();
}
inline void LimitResponse::set_allocated_node_id(std::string* node_id) {
  if (node_id != nullptr) {
    
  } else {
    
  }
  _impl_.node_id_.SetAllocated(node_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.node_id_.IsDefault()) {
    _impl_.node_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ratelimit.LimitResponse.node_id)
}

// -------------------------------------------------------------------

// SyncState

// string client_id = 1;
inline void SyncState::clear_client_id() {
  _impl_.client_id_.ClearToEmpty();
}
inline const std::string& SyncState::client_id() const {
  // @@protoc_insertion_point(field_get:ratelimit.SyncState.client_id)
  return _internal_client_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SyncState::set_client_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.client_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ratelimit.SyncState.client_id)
}
inline std::string* SyncState::mutable_client_id() {
  std::string* _s = _internal_mutable_client_id();
  // @@protoc_insertion_point(field_mutable:ratelimit.SyncState.client_id)
  return _s;
}
inline const std::string& SyncState::_internal_client_id() const {
  return _impl_.client_id_.Get();
}
inline void SyncState::_internal_set_client_id(const std::string& value) {
  
  _impl_.client_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SyncState::_internal_mutable_client_id() {
  
  return _impl_.client_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SyncState::release_client_id() {
  // @@protoc_insertion_point(field_release:ratelimit.SyncState.client_id)
  return _impl_.client_id_.Release();
}
inline void SyncState::set_allocated_client_id(std::string* client_id) {
  if (client_id != nullptr) {
    
  } else {
    
  }
  _impl_.client_id_.SetAllocated(client_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.client_id_.IsDefault()) {
    _impl_.client_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ratelimit.SyncState.client_id)
}

// int64 tokens = 2;
inline void SyncState::clear_tokens() {
  _impl_.tokens_ = int64_t{0};
}
inline int64_t SyncState::_internal_tokens() const {
  return _impl_.tokens_;
}
inline int64_t SyncState::tokens() const {
  // @@protoc_insertion_point(field_get:ratelimit.SyncState.tokens)
  return _internal_tokens();
}
inline void SyncState::_internal_set_tokens(int64_t value) {
  
  _impl_.tokens_ = value;
}
inline void SyncState::set_tokens(int64_t value) {
  _internal_set_tokens(value);
  // @@protoc_insertion_point(field_set:ratelimit.SyncState.tokens)
}

// int64 last_refill_timestamp = 3;
inline void SyncState::clear_last_refill_timestamp() {
  _impl_.last_refill_timestamp_ = int64_t{0};
}
inline int64_t SyncState::_internal_last_refill_timestamp() const {
  return _impl_.last_refill_timestamp_;
}
inline int64_t SyncState::last_refill_timestamp() const {
  // @@protoc_insertion_point(field_get:ratelimit.SyncState.last_refill_timestamp)
  return _internal_last_refill_timestamp();
}
inline void SyncState::_internal_set_last_refill_timestamp(int64_t value) {
  
  _impl_.last_refill_timestamp_ = value;
}
inline void SyncState::set_last_refill_timestamp(int64_t value) {
  _internal_set_last_refill_timestamp(value);
  // @@protoc_insertion_point(field_set:ratelimit.SyncState.last_refill_timestamp)
}

// string source_node_id = 4;
inline void SyncState::clear_source_node_id() {
  _impl_.source_node_id_.ClearToEmpty();
}
inline const std::string& SyncState::source_node_id() const {
  // @@protoc_insertion_point(field_get:ratelimit.SyncState.source_node_id)
  return _internal_source_node_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SyncState::set_source_node_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.source_node_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ratelimit.SyncState.source_node_id)
}
inline std::string* SyncState::mutable_source_node_id() {
  std::string* _s = _internal_mutable_source_node_id();
  // @@protoc_insertion_point(field_mutable:ratelimit.SyncState.source_node_id)
  return _s;
}
inline const std::string& SyncState::_internal_source_node_id() const {
  return _impl_.source_node_id_.Get();
}
inline void SyncState::_internal_set_source_node_id(const std::string& value) {
  
  _impl_.source_node_id_.Set(value, GetArenaForAllocation());
}
inline std::string* SyncState::_internal_mutable_source_node_id() {
  
  return _impl_.source_node_id_.Mutable(GetArenaForAllocation());
}
inline std::string* SyncState::release_source_node_id() {
  // @@protoc_insertion_point(field_release:ratelimit.SyncState.source_node_id)
  return _impl_.source_node_id_.Release();
}
inline void SyncState::set_allocated_source_node_id(std::string* source_node_id) {
  if (source_node_id != nullptr) {
    
  } else {
    
  }
  _impl_.source_node_id_.SetAllocated(source_node_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.source_node_id_.IsDefault()) {
    _impl_.source_node_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ratelimit.SyncState.source_node_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ratelimit

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fnode_2eproto
