// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: node.proto

#include "node.pb.h"
#include "node.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ratelimit {

static const char* RateLimiterService_method_names[] = {
  "/ratelimit.RateLimiterService/CheckLimit",
  "/ratelimit.RateLimiterService/SyncTokenState",
};

std::unique_ptr< RateLimiterService::Stub> RateLimiterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RateLimiterService::Stub> stub(new RateLimiterService::Stub(channel, options));
  return stub;
}

RateLimiterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CheckLimit_(RateLimiterService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SyncTokenState_(RateLimiterService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RateLimiterService::Stub::CheckLimit(::grpc::ClientContext* context, const ::ratelimit::LimitRequest& request, ::ratelimit::LimitResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ratelimit::LimitRequest, ::ratelimit::LimitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CheckLimit_, context, request, response);
}

void RateLimiterService::Stub::async::CheckLimit(::grpc::ClientContext* context, const ::ratelimit::LimitRequest* request, ::ratelimit::LimitResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ratelimit::LimitRequest, ::ratelimit::LimitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckLimit_, context, request, response, std::move(f));
}

void RateLimiterService::Stub::async::CheckLimit(::grpc::ClientContext* context, const ::ratelimit::LimitRequest* request, ::ratelimit::LimitResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckLimit_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>* RateLimiterService::Stub::PrepareAsyncCheckLimitRaw(::grpc::ClientContext* context, const ::ratelimit::LimitRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ratelimit::LimitResponse, ::ratelimit::LimitRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CheckLimit_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>* RateLimiterService::Stub::AsyncCheckLimitRaw(::grpc::ClientContext* context, const ::ratelimit::LimitRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCheckLimitRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RateLimiterService::Stub::SyncTokenState(::grpc::ClientContext* context, const ::ratelimit::SyncState& request, ::ratelimit::LimitResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ratelimit::SyncState, ::ratelimit::LimitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SyncTokenState_, context, request, response);
}

void RateLimiterService::Stub::async::SyncTokenState(::grpc::ClientContext* context, const ::ratelimit::SyncState* request, ::ratelimit::LimitResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ratelimit::SyncState, ::ratelimit::LimitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SyncTokenState_, context, request, response, std::move(f));
}

void RateLimiterService::Stub::async::SyncTokenState(::grpc::ClientContext* context, const ::ratelimit::SyncState* request, ::ratelimit::LimitResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SyncTokenState_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>* RateLimiterService::Stub::PrepareAsyncSyncTokenStateRaw(::grpc::ClientContext* context, const ::ratelimit::SyncState& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ratelimit::LimitResponse, ::ratelimit::SyncState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SyncTokenState_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>* RateLimiterService::Stub::AsyncSyncTokenStateRaw(::grpc::ClientContext* context, const ::ratelimit::SyncState& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSyncTokenStateRaw(context, request, cq);
  result->StartCall();
  return result;
}

RateLimiterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RateLimiterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RateLimiterService::Service, ::ratelimit::LimitRequest, ::ratelimit::LimitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RateLimiterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ratelimit::LimitRequest* req,
             ::ratelimit::LimitResponse* resp) {
               return service->CheckLimit(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RateLimiterService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RateLimiterService::Service, ::ratelimit::SyncState, ::ratelimit::LimitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RateLimiterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ratelimit::SyncState* req,
             ::ratelimit::LimitResponse* resp) {
               return service->SyncTokenState(ctx, req, resp);
             }, this)));
}

RateLimiterService::Service::~Service() {
}

::grpc::Status RateLimiterService::Service::CheckLimit(::grpc::ServerContext* context, const ::ratelimit::LimitRequest* request, ::ratelimit::LimitResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RateLimiterService::Service::SyncTokenState(::grpc::ServerContext* context, const ::ratelimit::SyncState* request, ::ratelimit::LimitResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ratelimit

