// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_node_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_node_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_node_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_node_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_node_2eproto;
namespace ratelimit {
class LimitRequest;
struct LimitRequestDefaultTypeInternal;
extern LimitRequestDefaultTypeInternal _LimitRequest_default_instance_;
class LimitResponse;
struct LimitResponseDefaultTypeInternal;
extern LimitResponseDefaultTypeInternal _LimitResponse_default_instance_;
class SyncState;
struct SyncStateDefaultTypeInternal;
extern SyncStateDefaultTypeInternal _SyncState_default_instance_;
}  // namespace ratelimit
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace ratelimit {

// ===================================================================


// -------------------------------------------------------------------

class SyncState final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ratelimit.SyncState) */ {
 public:
  inline SyncState() : SyncState(nullptr) {}
  ~SyncState() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR SyncState(::google::protobuf::internal::ConstantInitialized);

  inline SyncState(const SyncState& from)
      : SyncState(nullptr, from) {}
  SyncState(SyncState&& from) noexcept
    : SyncState() {
    *this = ::std::move(from);
  }

  inline SyncState& operator=(const SyncState& from) {
    CopyFrom(from);
    return *this;
  }
  inline SyncState& operator=(SyncState&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SyncState& default_instance() {
    return *internal_default_instance();
  }
  static inline const SyncState* internal_default_instance() {
    return reinterpret_cast<const SyncState*>(
               &_SyncState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SyncState& a, SyncState& b) {
    a.Swap(&b);
  }
  inline void Swap(SyncState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SyncState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SyncState* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SyncState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SyncState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const SyncState& from) {
    SyncState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(SyncState* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "ratelimit.SyncState";
  }
  protected:
  explicit SyncState(::google::protobuf::Arena* arena);
  SyncState(::google::protobuf::Arena* arena, const SyncState& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIdFieldNumber = 1,
    kSourceNodeIdFieldNumber = 4,
    kTokensFieldNumber = 2,
    kLastRefillTimestampFieldNumber = 3,
  };
  // string client_id = 1;
  void clear_client_id() ;
  const std::string& client_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_client_id(Arg_&& arg, Args_... args);
  std::string* mutable_client_id();
  PROTOBUF_NODISCARD std::string* release_client_id();
  void set_allocated_client_id(std::string* value);

  private:
  const std::string& _internal_client_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_client_id(
      const std::string& value);
  std::string* _internal_mutable_client_id();

  public:
  // string source_node_id = 4;
  void clear_source_node_id() ;
  const std::string& source_node_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_source_node_id(Arg_&& arg, Args_... args);
  std::string* mutable_source_node_id();
  PROTOBUF_NODISCARD std::string* release_source_node_id();
  void set_allocated_source_node_id(std::string* value);

  private:
  const std::string& _internal_source_node_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_source_node_id(
      const std::string& value);
  std::string* _internal_mutable_source_node_id();

  public:
  // int64 tokens = 2;
  void clear_tokens() ;
  ::int64_t tokens() const;
  void set_tokens(::int64_t value);

  private:
  ::int64_t _internal_tokens() const;
  void _internal_set_tokens(::int64_t value);

  public:
  // int64 last_refill_timestamp = 3;
  void clear_last_refill_timestamp() ;
  ::int64_t last_refill_timestamp() const;
  void set_last_refill_timestamp(::int64_t value);

  private:
  ::int64_t _internal_last_refill_timestamp() const;
  void _internal_set_last_refill_timestamp(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:ratelimit.SyncState)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      51, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr client_id_;
    ::google::protobuf::internal::ArenaStringPtr source_node_id_;
    ::int64_t tokens_;
    ::int64_t last_refill_timestamp_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_node_2eproto;
};// -------------------------------------------------------------------

class LimitResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ratelimit.LimitResponse) */ {
 public:
  inline LimitResponse() : LimitResponse(nullptr) {}
  ~LimitResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR LimitResponse(::google::protobuf::internal::ConstantInitialized);

  inline LimitResponse(const LimitResponse& from)
      : LimitResponse(nullptr, from) {}
  LimitResponse(LimitResponse&& from) noexcept
    : LimitResponse() {
    *this = ::std::move(from);
  }

  inline LimitResponse& operator=(const LimitResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline LimitResponse& operator=(LimitResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LimitResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const LimitResponse* internal_default_instance() {
    return reinterpret_cast<const LimitResponse*>(
               &_LimitResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LimitResponse& a, LimitResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(LimitResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LimitResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LimitResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LimitResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LimitResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const LimitResponse& from) {
    LimitResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(LimitResponse* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "ratelimit.LimitResponse";
  }
  protected:
  explicit LimitResponse(::google::protobuf::Arena* arena);
  LimitResponse(::google::protobuf::Arena* arena, const LimitResponse& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeIdFieldNumber = 4,
    kRemainingTokensFieldNumber = 2,
    kRetryAfterMsFieldNumber = 3,
    kAllowedFieldNumber = 1,
  };
  // string node_id = 4;
  void clear_node_id() ;
  const std::string& node_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_node_id(Arg_&& arg, Args_... args);
  std::string* mutable_node_id();
  PROTOBUF_NODISCARD std::string* release_node_id();
  void set_allocated_node_id(std::string* value);

  private:
  const std::string& _internal_node_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_node_id(
      const std::string& value);
  std::string* _internal_mutable_node_id();

  public:
  // int64 remaining_tokens = 2;
  void clear_remaining_tokens() ;
  ::int64_t remaining_tokens() const;
  void set_remaining_tokens(::int64_t value);

  private:
  ::int64_t _internal_remaining_tokens() const;
  void _internal_set_remaining_tokens(::int64_t value);

  public:
  // int64 retry_after_ms = 3;
  void clear_retry_after_ms() ;
  ::int64_t retry_after_ms() const;
  void set_retry_after_ms(::int64_t value);

  private:
  ::int64_t _internal_retry_after_ms() const;
  void _internal_set_retry_after_ms(::int64_t value);

  public:
  // bool allowed = 1;
  void clear_allowed() ;
  bool allowed() const;
  void set_allowed(bool value);

  private:
  bool _internal_allowed() const;
  void _internal_set_allowed(bool value);

  public:
  // @@protoc_insertion_point(class_scope:ratelimit.LimitResponse)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      39, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr node_id_;
    ::int64_t remaining_tokens_;
    ::int64_t retry_after_ms_;
    bool allowed_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_node_2eproto;
};// -------------------------------------------------------------------

class LimitRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ratelimit.LimitRequest) */ {
 public:
  inline LimitRequest() : LimitRequest(nullptr) {}
  ~LimitRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR LimitRequest(::google::protobuf::internal::ConstantInitialized);

  inline LimitRequest(const LimitRequest& from)
      : LimitRequest(nullptr, from) {}
  LimitRequest(LimitRequest&& from) noexcept
    : LimitRequest() {
    *this = ::std::move(from);
  }

  inline LimitRequest& operator=(const LimitRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LimitRequest& operator=(LimitRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LimitRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const LimitRequest* internal_default_instance() {
    return reinterpret_cast<const LimitRequest*>(
               &_LimitRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LimitRequest& a, LimitRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(LimitRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LimitRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LimitRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LimitRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LimitRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const LimitRequest& from) {
    LimitRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(LimitRequest* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "ratelimit.LimitRequest";
  }
  protected:
  explicit LimitRequest(::google::protobuf::Arena* arena);
  LimitRequest(::google::protobuf::Arena* arena, const LimitRequest& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIdFieldNumber = 1,
    kTokensRequestedFieldNumber = 2,
    kTimestampFieldNumber = 3,
  };
  // string client_id = 1;
  void clear_client_id() ;
  const std::string& client_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_client_id(Arg_&& arg, Args_... args);
  std::string* mutable_client_id();
  PROTOBUF_NODISCARD std::string* release_client_id();
  void set_allocated_client_id(std::string* value);

  private:
  const std::string& _internal_client_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_client_id(
      const std::string& value);
  std::string* _internal_mutable_client_id();

  public:
  // int64 tokens_requested = 2;
  void clear_tokens_requested() ;
  ::int64_t tokens_requested() const;
  void set_tokens_requested(::int64_t value);

  private:
  ::int64_t _internal_tokens_requested() const;
  void _internal_set_tokens_requested(::int64_t value);

  public:
  // int64 timestamp = 3;
  void clear_timestamp() ;
  ::int64_t timestamp() const;
  void set_timestamp(::int64_t value);

  private:
  ::int64_t _internal_timestamp() const;
  void _internal_set_timestamp(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:ratelimit.LimitRequest)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      40, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr client_id_;
    ::int64_t tokens_requested_;
    ::int64_t timestamp_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_node_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// LimitRequest

// string client_id = 1;
inline void LimitRequest::clear_client_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.client_id_.ClearToEmpty();
}
inline const std::string& LimitRequest::client_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ratelimit.LimitRequest.client_id)
  return _internal_client_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void LimitRequest::set_client_id(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.client_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ratelimit.LimitRequest.client_id)
}
inline std::string* LimitRequest::mutable_client_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_client_id();
  // @@protoc_insertion_point(field_mutable:ratelimit.LimitRequest.client_id)
  return _s;
}
inline const std::string& LimitRequest::_internal_client_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.client_id_.Get();
}
inline void LimitRequest::_internal_set_client_id(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.client_id_.Set(value, GetArena());
}
inline std::string* LimitRequest::_internal_mutable_client_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.client_id_.Mutable( GetArena());
}
inline std::string* LimitRequest::release_client_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:ratelimit.LimitRequest.client_id)
  return _impl_.client_id_.Release();
}
inline void LimitRequest::set_allocated_client_id(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.client_id_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.client_id_.IsDefault()) {
          _impl_.client_id_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ratelimit.LimitRequest.client_id)
}

// int64 tokens_requested = 2;
inline void LimitRequest::clear_tokens_requested() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tokens_requested_ = ::int64_t{0};
}
inline ::int64_t LimitRequest::tokens_requested() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitRequest.tokens_requested)
  return _internal_tokens_requested();
}
inline void LimitRequest::set_tokens_requested(::int64_t value) {
  _internal_set_tokens_requested(value);
  // @@protoc_insertion_point(field_set:ratelimit.LimitRequest.tokens_requested)
}
inline ::int64_t LimitRequest::_internal_tokens_requested() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.tokens_requested_;
}
inline void LimitRequest::_internal_set_tokens_requested(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.tokens_requested_ = value;
}

// int64 timestamp = 3;
inline void LimitRequest::clear_timestamp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.timestamp_ = ::int64_t{0};
}
inline ::int64_t LimitRequest::timestamp() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitRequest.timestamp)
  return _internal_timestamp();
}
inline void LimitRequest::set_timestamp(::int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:ratelimit.LimitRequest.timestamp)
}
inline ::int64_t LimitRequest::_internal_timestamp() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.timestamp_;
}
inline void LimitRequest::_internal_set_timestamp(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.timestamp_ = value;
}

// -------------------------------------------------------------------

// LimitResponse

// bool allowed = 1;
inline void LimitResponse::clear_allowed() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.allowed_ = false;
}
inline bool LimitResponse::allowed() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitResponse.allowed)
  return _internal_allowed();
}
inline void LimitResponse::set_allowed(bool value) {
  _internal_set_allowed(value);
  // @@protoc_insertion_point(field_set:ratelimit.LimitResponse.allowed)
}
inline bool LimitResponse::_internal_allowed() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.allowed_;
}
inline void LimitResponse::_internal_set_allowed(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.allowed_ = value;
}

// int64 remaining_tokens = 2;
inline void LimitResponse::clear_remaining_tokens() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.remaining_tokens_ = ::int64_t{0};
}
inline ::int64_t LimitResponse::remaining_tokens() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitResponse.remaining_tokens)
  return _internal_remaining_tokens();
}
inline void LimitResponse::set_remaining_tokens(::int64_t value) {
  _internal_set_remaining_tokens(value);
  // @@protoc_insertion_point(field_set:ratelimit.LimitResponse.remaining_tokens)
}
inline ::int64_t LimitResponse::_internal_remaining_tokens() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.remaining_tokens_;
}
inline void LimitResponse::_internal_set_remaining_tokens(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.remaining_tokens_ = value;
}

// int64 retry_after_ms = 3;
inline void LimitResponse::clear_retry_after_ms() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.retry_after_ms_ = ::int64_t{0};
}
inline ::int64_t LimitResponse::retry_after_ms() const {
  // @@protoc_insertion_point(field_get:ratelimit.LimitResponse.retry_after_ms)
  return _internal_retry_after_ms();
}
inline void LimitResponse::set_retry_after_ms(::int64_t value) {
  _internal_set_retry_after_ms(value);
  // @@protoc_insertion_point(field_set:ratelimit.LimitResponse.retry_after_ms)
}
inline ::int64_t LimitResponse::_internal_retry_after_ms() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.retry_after_ms_;
}
inline void LimitResponse::_internal_set_retry_after_ms(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.retry_after_ms_ = value;
}

// string node_id = 4;
inline void LimitResponse::clear_node_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.node_id_.ClearToEmpty();
}
inline const std::string& LimitResponse::node_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ratelimit.LimitResponse.node_id)
  return _internal_node_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void LimitResponse::set_node_id(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.node_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ratelimit.LimitResponse.node_id)
}
inline std::string* LimitResponse::mutable_node_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_node_id();
  // @@protoc_insertion_point(field_mutable:ratelimit.LimitResponse.node_id)
  return _s;
}
inline const std::string& LimitResponse::_internal_node_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.node_id_.Get();
}
inline void LimitResponse::_internal_set_node_id(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.node_id_.Set(value, GetArena());
}
inline std::string* LimitResponse::_internal_mutable_node_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.node_id_.Mutable( GetArena());
}
inline std::string* LimitResponse::release_node_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:ratelimit.LimitResponse.node_id)
  return _impl_.node_id_.Release();
}
inline void LimitResponse::set_allocated_node_id(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.node_id_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.node_id_.IsDefault()) {
          _impl_.node_id_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ratelimit.LimitResponse.node_id)
}

// -------------------------------------------------------------------

// SyncState

// string client_id = 1;
inline void SyncState::clear_client_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.client_id_.ClearToEmpty();
}
inline const std::string& SyncState::client_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ratelimit.SyncState.client_id)
  return _internal_client_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SyncState::set_client_id(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.client_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ratelimit.SyncState.client_id)
}
inline std::string* SyncState::mutable_client_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_client_id();
  // @@protoc_insertion_point(field_mutable:ratelimit.SyncState.client_id)
  return _s;
}
inline const std::string& SyncState::_internal_client_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.client_id_.Get();
}
inline void SyncState::_internal_set_client_id(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.client_id_.Set(value, GetArena());
}
inline std::string* SyncState::_internal_mutable_client_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.client_id_.Mutable( GetArena());
}
inline std::string* SyncState::release_client_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:ratelimit.SyncState.client_id)
  return _impl_.client_id_.Release();
}
inline void SyncState::set_allocated_client_id(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.client_id_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.client_id_.IsDefault()) {
          _impl_.client_id_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ratelimit.SyncState.client_id)
}

// int64 tokens = 2;
inline void SyncState::clear_tokens() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tokens_ = ::int64_t{0};
}
inline ::int64_t SyncState::tokens() const {
  // @@protoc_insertion_point(field_get:ratelimit.SyncState.tokens)
  return _internal_tokens();
}
inline void SyncState::set_tokens(::int64_t value) {
  _internal_set_tokens(value);
  // @@protoc_insertion_point(field_set:ratelimit.SyncState.tokens)
}
inline ::int64_t SyncState::_internal_tokens() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.tokens_;
}
inline void SyncState::_internal_set_tokens(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.tokens_ = value;
}

// int64 last_refill_timestamp = 3;
inline void SyncState::clear_last_refill_timestamp() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.last_refill_timestamp_ = ::int64_t{0};
}
inline ::int64_t SyncState::last_refill_timestamp() const {
  // @@protoc_insertion_point(field_get:ratelimit.SyncState.last_refill_timestamp)
  return _internal_last_refill_timestamp();
}
inline void SyncState::set_last_refill_timestamp(::int64_t value) {
  _internal_set_last_refill_timestamp(value);
  // @@protoc_insertion_point(field_set:ratelimit.SyncState.last_refill_timestamp)
}
inline ::int64_t SyncState::_internal_last_refill_timestamp() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.last_refill_timestamp_;
}
inline void SyncState::_internal_set_last_refill_timestamp(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.last_refill_timestamp_ = value;
}

// string source_node_id = 4;
inline void SyncState::clear_source_node_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.source_node_id_.ClearToEmpty();
}
inline const std::string& SyncState::source_node_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ratelimit.SyncState.source_node_id)
  return _internal_source_node_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SyncState::set_source_node_id(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.source_node_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ratelimit.SyncState.source_node_id)
}
inline std::string* SyncState::mutable_source_node_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_source_node_id();
  // @@protoc_insertion_point(field_mutable:ratelimit.SyncState.source_node_id)
  return _s;
}
inline const std::string& SyncState::_internal_source_node_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.source_node_id_.Get();
}
inline void SyncState::_internal_set_source_node_id(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.source_node_id_.Set(value, GetArena());
}
inline std::string* SyncState::_internal_mutable_source_node_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.source_node_id_.Mutable( GetArena());
}
inline std::string* SyncState::release_source_node_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:ratelimit.SyncState.source_node_id)
  return _impl_.source_node_id_.Release();
}
inline void SyncState::set_allocated_source_node_id(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.source_node_id_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.source_node_id_.IsDefault()) {
          _impl_.source_node_id_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ratelimit.SyncState.source_node_id)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace ratelimit


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_node_2eproto_2epb_2eh
