// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: node.proto
#ifndef GRPC_node_2eproto__INCLUDED
#define GRPC_node_2eproto__INCLUDED

#include "node.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ratelimit {

class RateLimiterService final {
 public:
  static constexpr char const* service_full_name() {
    return "ratelimit.RateLimiterService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CheckLimit(::grpc::ClientContext* context, const ::ratelimit::LimitRequest& request, ::ratelimit::LimitResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ratelimit::LimitResponse>> AsyncCheckLimit(::grpc::ClientContext* context, const ::ratelimit::LimitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ratelimit::LimitResponse>>(AsyncCheckLimitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ratelimit::LimitResponse>> PrepareAsyncCheckLimit(::grpc::ClientContext* context, const ::ratelimit::LimitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ratelimit::LimitResponse>>(PrepareAsyncCheckLimitRaw(context, request, cq));
    }
    virtual ::grpc::Status SyncTokenState(::grpc::ClientContext* context, const ::ratelimit::SyncState& request, ::ratelimit::LimitResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ratelimit::LimitResponse>> AsyncSyncTokenState(::grpc::ClientContext* context, const ::ratelimit::SyncState& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ratelimit::LimitResponse>>(AsyncSyncTokenStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ratelimit::LimitResponse>> PrepareAsyncSyncTokenState(::grpc::ClientContext* context, const ::ratelimit::SyncState& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ratelimit::LimitResponse>>(PrepareAsyncSyncTokenStateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CheckLimit(::grpc::ClientContext* context, const ::ratelimit::LimitRequest* request, ::ratelimit::LimitResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CheckLimit(::grpc::ClientContext* context, const ::ratelimit::LimitRequest* request, ::ratelimit::LimitResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SyncTokenState(::grpc::ClientContext* context, const ::ratelimit::SyncState* request, ::ratelimit::LimitResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SyncTokenState(::grpc::ClientContext* context, const ::ratelimit::SyncState* request, ::ratelimit::LimitResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ratelimit::LimitResponse>* AsyncCheckLimitRaw(::grpc::ClientContext* context, const ::ratelimit::LimitRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ratelimit::LimitResponse>* PrepareAsyncCheckLimitRaw(::grpc::ClientContext* context, const ::ratelimit::LimitRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ratelimit::LimitResponse>* AsyncSyncTokenStateRaw(::grpc::ClientContext* context, const ::ratelimit::SyncState& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ratelimit::LimitResponse>* PrepareAsyncSyncTokenStateRaw(::grpc::ClientContext* context, const ::ratelimit::SyncState& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CheckLimit(::grpc::ClientContext* context, const ::ratelimit::LimitRequest& request, ::ratelimit::LimitResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>> AsyncCheckLimit(::grpc::ClientContext* context, const ::ratelimit::LimitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>>(AsyncCheckLimitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>> PrepareAsyncCheckLimit(::grpc::ClientContext* context, const ::ratelimit::LimitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>>(PrepareAsyncCheckLimitRaw(context, request, cq));
    }
    ::grpc::Status SyncTokenState(::grpc::ClientContext* context, const ::ratelimit::SyncState& request, ::ratelimit::LimitResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>> AsyncSyncTokenState(::grpc::ClientContext* context, const ::ratelimit::SyncState& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>>(AsyncSyncTokenStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>> PrepareAsyncSyncTokenState(::grpc::ClientContext* context, const ::ratelimit::SyncState& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>>(PrepareAsyncSyncTokenStateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CheckLimit(::grpc::ClientContext* context, const ::ratelimit::LimitRequest* request, ::ratelimit::LimitResponse* response, std::function<void(::grpc::Status)>) override;
      void CheckLimit(::grpc::ClientContext* context, const ::ratelimit::LimitRequest* request, ::ratelimit::LimitResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SyncTokenState(::grpc::ClientContext* context, const ::ratelimit::SyncState* request, ::ratelimit::LimitResponse* response, std::function<void(::grpc::Status)>) override;
      void SyncTokenState(::grpc::ClientContext* context, const ::ratelimit::SyncState* request, ::ratelimit::LimitResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>* AsyncCheckLimitRaw(::grpc::ClientContext* context, const ::ratelimit::LimitRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>* PrepareAsyncCheckLimitRaw(::grpc::ClientContext* context, const ::ratelimit::LimitRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>* AsyncSyncTokenStateRaw(::grpc::ClientContext* context, const ::ratelimit::SyncState& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ratelimit::LimitResponse>* PrepareAsyncSyncTokenStateRaw(::grpc::ClientContext* context, const ::ratelimit::SyncState& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CheckLimit_;
    const ::grpc::internal::RpcMethod rpcmethod_SyncTokenState_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CheckLimit(::grpc::ServerContext* context, const ::ratelimit::LimitRequest* request, ::ratelimit::LimitResponse* response);
    virtual ::grpc::Status SyncTokenState(::grpc::ServerContext* context, const ::ratelimit::SyncState* request, ::ratelimit::LimitResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CheckLimit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CheckLimit() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CheckLimit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckLimit(::grpc::ServerContext* /*context*/, const ::ratelimit::LimitRequest* /*request*/, ::ratelimit::LimitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckLimit(::grpc::ServerContext* context, ::ratelimit::LimitRequest* request, ::grpc::ServerAsyncResponseWriter< ::ratelimit::LimitResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SyncTokenState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SyncTokenState() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SyncTokenState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncTokenState(::grpc::ServerContext* /*context*/, const ::ratelimit::SyncState* /*request*/, ::ratelimit::LimitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSyncTokenState(::grpc::ServerContext* context, ::ratelimit::SyncState* request, ::grpc::ServerAsyncResponseWriter< ::ratelimit::LimitResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CheckLimit<WithAsyncMethod_SyncTokenState<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CheckLimit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CheckLimit() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ratelimit::LimitRequest, ::ratelimit::LimitResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ratelimit::LimitRequest* request, ::ratelimit::LimitResponse* response) { return this->CheckLimit(context, request, response); }));}
    void SetMessageAllocatorFor_CheckLimit(
        ::grpc::MessageAllocator< ::ratelimit::LimitRequest, ::ratelimit::LimitResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ratelimit::LimitRequest, ::ratelimit::LimitResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CheckLimit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckLimit(::grpc::ServerContext* /*context*/, const ::ratelimit::LimitRequest* /*request*/, ::ratelimit::LimitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckLimit(
      ::grpc::CallbackServerContext* /*context*/, const ::ratelimit::LimitRequest* /*request*/, ::ratelimit::LimitResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SyncTokenState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SyncTokenState() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ratelimit::SyncState, ::ratelimit::LimitResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ratelimit::SyncState* request, ::ratelimit::LimitResponse* response) { return this->SyncTokenState(context, request, response); }));}
    void SetMessageAllocatorFor_SyncTokenState(
        ::grpc::MessageAllocator< ::ratelimit::SyncState, ::ratelimit::LimitResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ratelimit::SyncState, ::ratelimit::LimitResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SyncTokenState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncTokenState(::grpc::ServerContext* /*context*/, const ::ratelimit::SyncState* /*request*/, ::ratelimit::LimitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SyncTokenState(
      ::grpc::CallbackServerContext* /*context*/, const ::ratelimit::SyncState* /*request*/, ::ratelimit::LimitResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CheckLimit<WithCallbackMethod_SyncTokenState<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CheckLimit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CheckLimit() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CheckLimit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckLimit(::grpc::ServerContext* /*context*/, const ::ratelimit::LimitRequest* /*request*/, ::ratelimit::LimitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SyncTokenState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SyncTokenState() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SyncTokenState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncTokenState(::grpc::ServerContext* /*context*/, const ::ratelimit::SyncState* /*request*/, ::ratelimit::LimitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CheckLimit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CheckLimit() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CheckLimit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckLimit(::grpc::ServerContext* /*context*/, const ::ratelimit::LimitRequest* /*request*/, ::ratelimit::LimitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckLimit(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SyncTokenState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SyncTokenState() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SyncTokenState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncTokenState(::grpc::ServerContext* /*context*/, const ::ratelimit::SyncState* /*request*/, ::ratelimit::LimitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSyncTokenState(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CheckLimit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CheckLimit() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CheckLimit(context, request, response); }));
    }
    ~WithRawCallbackMethod_CheckLimit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckLimit(::grpc::ServerContext* /*context*/, const ::ratelimit::LimitRequest* /*request*/, ::ratelimit::LimitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckLimit(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SyncTokenState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SyncTokenState() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SyncTokenState(context, request, response); }));
    }
    ~WithRawCallbackMethod_SyncTokenState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncTokenState(::grpc::ServerContext* /*context*/, const ::ratelimit::SyncState* /*request*/, ::ratelimit::LimitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SyncTokenState(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CheckLimit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CheckLimit() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ratelimit::LimitRequest, ::ratelimit::LimitResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ratelimit::LimitRequest, ::ratelimit::LimitResponse>* streamer) {
                       return this->StreamedCheckLimit(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CheckLimit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CheckLimit(::grpc::ServerContext* /*context*/, const ::ratelimit::LimitRequest* /*request*/, ::ratelimit::LimitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCheckLimit(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ratelimit::LimitRequest,::ratelimit::LimitResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SyncTokenState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SyncTokenState() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ratelimit::SyncState, ::ratelimit::LimitResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ratelimit::SyncState, ::ratelimit::LimitResponse>* streamer) {
                       return this->StreamedSyncTokenState(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SyncTokenState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SyncTokenState(::grpc::ServerContext* /*context*/, const ::ratelimit::SyncState* /*request*/, ::ratelimit::LimitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSyncTokenState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ratelimit::SyncState,::ratelimit::LimitResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CheckLimit<WithStreamedUnaryMethod_SyncTokenState<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CheckLimit<WithStreamedUnaryMethod_SyncTokenState<Service > > StreamedService;
};

}  // namespace ratelimit


#endif  // GRPC_node_2eproto__INCLUDED
