// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/node.proto

#include "proto/node.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ratelimit {
PROTOBUF_CONSTEXPR LimitState::LimitState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.client_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.tokens_)*/int64_t{0}
  , /*decltype(_impl_.last_refill_timestamp_)*/int64_t{0}
  , /*decltype(_impl_.capacity_)*/int64_t{0}
  , /*decltype(_impl_.refill_rate_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LimitStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LimitStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LimitStateDefaultTypeInternal() {}
  union {
    LimitState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LimitStateDefaultTypeInternal _LimitState_default_instance_;
PROTOBUF_CONSTEXPR LimitRequest::LimitRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.client_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.tokens_requested_)*/int64_t{0}
  , /*decltype(_impl_.timestamp_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LimitRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LimitRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LimitRequestDefaultTypeInternal() {}
  union {
    LimitRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LimitRequestDefaultTypeInternal _LimitRequest_default_instance_;
PROTOBUF_CONSTEXPR LimitResponse::LimitResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.node_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.remaining_tokens_)*/int64_t{0}
  , /*decltype(_impl_.retry_after_ms_)*/int64_t{0}
  , /*decltype(_impl_.allowed_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LimitResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LimitResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LimitResponseDefaultTypeInternal() {}
  union {
    LimitResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LimitResponseDefaultTypeInternal _LimitResponse_default_instance_;
PROTOBUF_CONSTEXPR SyncState::SyncState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.client_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.source_node_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.tokens_)*/int64_t{0}
  , /*decltype(_impl_.last_refill_timestamp_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SyncStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SyncStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SyncStateDefaultTypeInternal() {}
  union {
    SyncState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SyncStateDefaultTypeInternal _SyncState_default_instance_;
}  // namespace ratelimit
static ::_pb::Metadata file_level_metadata_proto_2fnode_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_proto_2fnode_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2fnode_2eproto = nullptr;

const uint32_t TableStruct_proto_2fnode_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitState, _impl_.client_id_),
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitState, _impl_.tokens_),
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitState, _impl_.last_refill_timestamp_),
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitState, _impl_.capacity_),
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitState, _impl_.refill_rate_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitRequest, _impl_.client_id_),
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitRequest, _impl_.tokens_requested_),
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitRequest, _impl_.timestamp_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitResponse, _impl_.allowed_),
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitResponse, _impl_.remaining_tokens_),
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitResponse, _impl_.retry_after_ms_),
  PROTOBUF_FIELD_OFFSET(::ratelimit::LimitResponse, _impl_.node_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ratelimit::SyncState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ratelimit::SyncState, _impl_.client_id_),
  PROTOBUF_FIELD_OFFSET(::ratelimit::SyncState, _impl_.tokens_),
  PROTOBUF_FIELD_OFFSET(::ratelimit::SyncState, _impl_.last_refill_timestamp_),
  PROTOBUF_FIELD_OFFSET(::ratelimit::SyncState, _impl_.source_node_id_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ratelimit::LimitState)},
  { 11, -1, -1, sizeof(::ratelimit::LimitRequest)},
  { 20, -1, -1, sizeof(::ratelimit::LimitResponse)},
  { 30, -1, -1, sizeof(::ratelimit::SyncState)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ratelimit::_LimitState_default_instance_._instance,
  &::ratelimit::_LimitRequest_default_instance_._instance,
  &::ratelimit::_LimitResponse_default_instance_._instance,
  &::ratelimit::_SyncState_default_instance_._instance,
};

const char descriptor_table_protodef_proto_2fnode_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020proto/node.proto\022\tratelimit\"u\n\nLimitSt"
  "ate\022\021\n\tclient_id\030\001 \001(\t\022\016\n\006tokens\030\002 \001(\003\022\035"
  "\n\025last_refill_timestamp\030\003 \001(\003\022\020\n\010capacit"
  "y\030\004 \001(\003\022\023\n\013refill_rate\030\005 \001(\001\"N\n\014LimitReq"
  "uest\022\021\n\tclient_id\030\001 \001(\t\022\030\n\020tokens_reques"
  "ted\030\002 \001(\003\022\021\n\ttimestamp\030\003 \001(\003\"c\n\rLimitRes"
  "ponse\022\017\n\007allowed\030\001 \001(\010\022\030\n\020remaining_toke"
  "ns\030\002 \001(\003\022\026\n\016retry_after_ms\030\003 \001(\003\022\017\n\007node"
  "_id\030\004 \001(\t\"e\n\tSyncState\022\021\n\tclient_id\030\001 \001("
  "\t\022\016\n\006tokens\030\002 \001(\003\022\035\n\025last_refill_timesta"
  "mp\030\003 \001(\003\022\026\n\016source_node_id\030\004 \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_proto_2fnode_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fnode_2eproto = {
    false, false, 440, descriptor_table_protodef_proto_2fnode_2eproto,
    "proto/node.proto",
    &descriptor_table_proto_2fnode_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_proto_2fnode_2eproto::offsets,
    file_level_metadata_proto_2fnode_2eproto, file_level_enum_descriptors_proto_2fnode_2eproto,
    file_level_service_descriptors_proto_2fnode_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fnode_2eproto_getter() {
  return &descriptor_table_proto_2fnode_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fnode_2eproto(&descriptor_table_proto_2fnode_2eproto);
namespace ratelimit {

// ===================================================================

class LimitState::_Internal {
 public:
};

LimitState::LimitState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ratelimit.LimitState)
}
LimitState::LimitState(const LimitState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LimitState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.client_id_){}
    , decltype(_impl_.tokens_){}
    , decltype(_impl_.last_refill_timestamp_){}
    , decltype(_impl_.capacity_){}
    , decltype(_impl_.refill_rate_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.client_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.client_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_client_id().empty()) {
    _this->_impl_.client_id_.Set(from._internal_client_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.tokens_, &from._impl_.tokens_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.refill_rate_) -
    reinterpret_cast<char*>(&_impl_.tokens_)) + sizeof(_impl_.refill_rate_));
  // @@protoc_insertion_point(copy_constructor:ratelimit.LimitState)
}

inline void LimitState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.client_id_){}
    , decltype(_impl_.tokens_){int64_t{0}}
    , decltype(_impl_.last_refill_timestamp_){int64_t{0}}
    , decltype(_impl_.capacity_){int64_t{0}}
    , decltype(_impl_.refill_rate_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.client_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.client_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LimitState::~LimitState() {
  // @@protoc_insertion_point(destructor:ratelimit.LimitState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LimitState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.client_id_.Destroy();
}

void LimitState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LimitState::Clear() {
// @@protoc_insertion_point(message_clear_start:ratelimit.LimitState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.client_id_.ClearToEmpty();
  ::memset(&_impl_.tokens_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.refill_rate_) -
      reinterpret_cast<char*>(&_impl_.tokens_)) + sizeof(_impl_.refill_rate_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LimitState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string client_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_client_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ratelimit.LimitState.client_id"));
        } else
          goto handle_unusual;
        continue;
      // int64 tokens = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.tokens_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 last_refill_timestamp = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.last_refill_timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 capacity = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.capacity_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double refill_rate = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _impl_.refill_rate_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LimitState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ratelimit.LimitState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string client_id = 1;
  if (!this->_internal_client_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_client_id().data(), static_cast<int>(this->_internal_client_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ratelimit.LimitState.client_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_client_id(), target);
  }

  // int64 tokens = 2;
  if (this->_internal_tokens() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_tokens(), target);
  }

  // int64 last_refill_timestamp = 3;
  if (this->_internal_last_refill_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_last_refill_timestamp(), target);
  }

  // int64 capacity = 4;
  if (this->_internal_capacity() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_capacity(), target);
  }

  // double refill_rate = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_refill_rate = this->_internal_refill_rate();
  uint64_t raw_refill_rate;
  memcpy(&raw_refill_rate, &tmp_refill_rate, sizeof(tmp_refill_rate));
  if (raw_refill_rate != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_refill_rate(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ratelimit.LimitState)
  return target;
}

size_t LimitState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ratelimit.LimitState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string client_id = 1;
  if (!this->_internal_client_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_client_id());
  }

  // int64 tokens = 2;
  if (this->_internal_tokens() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_tokens());
  }

  // int64 last_refill_timestamp = 3;
  if (this->_internal_last_refill_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_last_refill_timestamp());
  }

  // int64 capacity = 4;
  if (this->_internal_capacity() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_capacity());
  }

  // double refill_rate = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_refill_rate = this->_internal_refill_rate();
  uint64_t raw_refill_rate;
  memcpy(&raw_refill_rate, &tmp_refill_rate, sizeof(tmp_refill_rate));
  if (raw_refill_rate != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LimitState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LimitState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LimitState::GetClassData() const { return &_class_data_; }


void LimitState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LimitState*>(&to_msg);
  auto& from = static_cast<const LimitState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ratelimit.LimitState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_client_id().empty()) {
    _this->_internal_set_client_id(from._internal_client_id());
  }
  if (from._internal_tokens() != 0) {
    _this->_internal_set_tokens(from._internal_tokens());
  }
  if (from._internal_last_refill_timestamp() != 0) {
    _this->_internal_set_last_refill_timestamp(from._internal_last_refill_timestamp());
  }
  if (from._internal_capacity() != 0) {
    _this->_internal_set_capacity(from._internal_capacity());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_refill_rate = from._internal_refill_rate();
  uint64_t raw_refill_rate;
  memcpy(&raw_refill_rate, &tmp_refill_rate, sizeof(tmp_refill_rate));
  if (raw_refill_rate != 0) {
    _this->_internal_set_refill_rate(from._internal_refill_rate());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LimitState::CopyFrom(const LimitState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ratelimit.LimitState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LimitState::IsInitialized() const {
  return true;
}

void LimitState::InternalSwap(LimitState* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.client_id_, lhs_arena,
      &other->_impl_.client_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LimitState, _impl_.refill_rate_)
      + sizeof(LimitState::_impl_.refill_rate_)
      - PROTOBUF_FIELD_OFFSET(LimitState, _impl_.tokens_)>(
          reinterpret_cast<char*>(&_impl_.tokens_),
          reinterpret_cast<char*>(&other->_impl_.tokens_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LimitState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fnode_2eproto_getter, &descriptor_table_proto_2fnode_2eproto_once,
      file_level_metadata_proto_2fnode_2eproto[0]);
}

// ===================================================================

class LimitRequest::_Internal {
 public:
};

LimitRequest::LimitRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ratelimit.LimitRequest)
}
LimitRequest::LimitRequest(const LimitRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LimitRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.client_id_){}
    , decltype(_impl_.tokens_requested_){}
    , decltype(_impl_.timestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.client_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.client_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_client_id().empty()) {
    _this->_impl_.client_id_.Set(from._internal_client_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.tokens_requested_, &from._impl_.tokens_requested_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.timestamp_) -
    reinterpret_cast<char*>(&_impl_.tokens_requested_)) + sizeof(_impl_.timestamp_));
  // @@protoc_insertion_point(copy_constructor:ratelimit.LimitRequest)
}

inline void LimitRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.client_id_){}
    , decltype(_impl_.tokens_requested_){int64_t{0}}
    , decltype(_impl_.timestamp_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.client_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.client_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LimitRequest::~LimitRequest() {
  // @@protoc_insertion_point(destructor:ratelimit.LimitRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LimitRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.client_id_.Destroy();
}

void LimitRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LimitRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ratelimit.LimitRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.client_id_.ClearToEmpty();
  ::memset(&_impl_.tokens_requested_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.timestamp_) -
      reinterpret_cast<char*>(&_impl_.tokens_requested_)) + sizeof(_impl_.timestamp_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LimitRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string client_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_client_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ratelimit.LimitRequest.client_id"));
        } else
          goto handle_unusual;
        continue;
      // int64 tokens_requested = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.tokens_requested_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 timestamp = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LimitRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ratelimit.LimitRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string client_id = 1;
  if (!this->_internal_client_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_client_id().data(), static_cast<int>(this->_internal_client_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ratelimit.LimitRequest.client_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_client_id(), target);
  }

  // int64 tokens_requested = 2;
  if (this->_internal_tokens_requested() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_tokens_requested(), target);
  }

  // int64 timestamp = 3;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_timestamp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ratelimit.LimitRequest)
  return target;
}

size_t LimitRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ratelimit.LimitRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string client_id = 1;
  if (!this->_internal_client_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_client_id());
  }

  // int64 tokens_requested = 2;
  if (this->_internal_tokens_requested() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_tokens_requested());
  }

  // int64 timestamp = 3;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LimitRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LimitRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LimitRequest::GetClassData() const { return &_class_data_; }


void LimitRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LimitRequest*>(&to_msg);
  auto& from = static_cast<const LimitRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ratelimit.LimitRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_client_id().empty()) {
    _this->_internal_set_client_id(from._internal_client_id());
  }
  if (from._internal_tokens_requested() != 0) {
    _this->_internal_set_tokens_requested(from._internal_tokens_requested());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LimitRequest::CopyFrom(const LimitRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ratelimit.LimitRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LimitRequest::IsInitialized() const {
  return true;
}

void LimitRequest::InternalSwap(LimitRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.client_id_, lhs_arena,
      &other->_impl_.client_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LimitRequest, _impl_.timestamp_)
      + sizeof(LimitRequest::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(LimitRequest, _impl_.tokens_requested_)>(
          reinterpret_cast<char*>(&_impl_.tokens_requested_),
          reinterpret_cast<char*>(&other->_impl_.tokens_requested_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LimitRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fnode_2eproto_getter, &descriptor_table_proto_2fnode_2eproto_once,
      file_level_metadata_proto_2fnode_2eproto[1]);
}

// ===================================================================

class LimitResponse::_Internal {
 public:
};

LimitResponse::LimitResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ratelimit.LimitResponse)
}
LimitResponse::LimitResponse(const LimitResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LimitResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.node_id_){}
    , decltype(_impl_.remaining_tokens_){}
    , decltype(_impl_.retry_after_ms_){}
    , decltype(_impl_.allowed_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.node_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.node_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_node_id().empty()) {
    _this->_impl_.node_id_.Set(from._internal_node_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.remaining_tokens_, &from._impl_.remaining_tokens_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.allowed_) -
    reinterpret_cast<char*>(&_impl_.remaining_tokens_)) + sizeof(_impl_.allowed_));
  // @@protoc_insertion_point(copy_constructor:ratelimit.LimitResponse)
}

inline void LimitResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.node_id_){}
    , decltype(_impl_.remaining_tokens_){int64_t{0}}
    , decltype(_impl_.retry_after_ms_){int64_t{0}}
    , decltype(_impl_.allowed_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.node_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.node_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LimitResponse::~LimitResponse() {
  // @@protoc_insertion_point(destructor:ratelimit.LimitResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LimitResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.node_id_.Destroy();
}

void LimitResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LimitResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ratelimit.LimitResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.node_id_.ClearToEmpty();
  ::memset(&_impl_.remaining_tokens_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.allowed_) -
      reinterpret_cast<char*>(&_impl_.remaining_tokens_)) + sizeof(_impl_.allowed_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LimitResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool allowed = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.allowed_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 remaining_tokens = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.remaining_tokens_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 retry_after_ms = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.retry_after_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string node_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_node_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ratelimit.LimitResponse.node_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LimitResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ratelimit.LimitResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool allowed = 1;
  if (this->_internal_allowed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_allowed(), target);
  }

  // int64 remaining_tokens = 2;
  if (this->_internal_remaining_tokens() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_remaining_tokens(), target);
  }

  // int64 retry_after_ms = 3;
  if (this->_internal_retry_after_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_retry_after_ms(), target);
  }

  // string node_id = 4;
  if (!this->_internal_node_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_node_id().data(), static_cast<int>(this->_internal_node_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ratelimit.LimitResponse.node_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_node_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ratelimit.LimitResponse)
  return target;
}

size_t LimitResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ratelimit.LimitResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string node_id = 4;
  if (!this->_internal_node_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_node_id());
  }

  // int64 remaining_tokens = 2;
  if (this->_internal_remaining_tokens() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_remaining_tokens());
  }

  // int64 retry_after_ms = 3;
  if (this->_internal_retry_after_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_retry_after_ms());
  }

  // bool allowed = 1;
  if (this->_internal_allowed() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LimitResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LimitResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LimitResponse::GetClassData() const { return &_class_data_; }


void LimitResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LimitResponse*>(&to_msg);
  auto& from = static_cast<const LimitResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ratelimit.LimitResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_node_id().empty()) {
    _this->_internal_set_node_id(from._internal_node_id());
  }
  if (from._internal_remaining_tokens() != 0) {
    _this->_internal_set_remaining_tokens(from._internal_remaining_tokens());
  }
  if (from._internal_retry_after_ms() != 0) {
    _this->_internal_set_retry_after_ms(from._internal_retry_after_ms());
  }
  if (from._internal_allowed() != 0) {
    _this->_internal_set_allowed(from._internal_allowed());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LimitResponse::CopyFrom(const LimitResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ratelimit.LimitResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LimitResponse::IsInitialized() const {
  return true;
}

void LimitResponse::InternalSwap(LimitResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.node_id_, lhs_arena,
      &other->_impl_.node_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LimitResponse, _impl_.allowed_)
      + sizeof(LimitResponse::_impl_.allowed_)
      - PROTOBUF_FIELD_OFFSET(LimitResponse, _impl_.remaining_tokens_)>(
          reinterpret_cast<char*>(&_impl_.remaining_tokens_),
          reinterpret_cast<char*>(&other->_impl_.remaining_tokens_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LimitResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fnode_2eproto_getter, &descriptor_table_proto_2fnode_2eproto_once,
      file_level_metadata_proto_2fnode_2eproto[2]);
}

// ===================================================================

class SyncState::_Internal {
 public:
};

SyncState::SyncState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ratelimit.SyncState)
}
SyncState::SyncState(const SyncState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SyncState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.client_id_){}
    , decltype(_impl_.source_node_id_){}
    , decltype(_impl_.tokens_){}
    , decltype(_impl_.last_refill_timestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.client_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.client_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_client_id().empty()) {
    _this->_impl_.client_id_.Set(from._internal_client_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.source_node_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.source_node_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_source_node_id().empty()) {
    _this->_impl_.source_node_id_.Set(from._internal_source_node_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.tokens_, &from._impl_.tokens_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.last_refill_timestamp_) -
    reinterpret_cast<char*>(&_impl_.tokens_)) + sizeof(_impl_.last_refill_timestamp_));
  // @@protoc_insertion_point(copy_constructor:ratelimit.SyncState)
}

inline void SyncState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.client_id_){}
    , decltype(_impl_.source_node_id_){}
    , decltype(_impl_.tokens_){int64_t{0}}
    , decltype(_impl_.last_refill_timestamp_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.client_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.client_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.source_node_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.source_node_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SyncState::~SyncState() {
  // @@protoc_insertion_point(destructor:ratelimit.SyncState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SyncState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.client_id_.Destroy();
  _impl_.source_node_id_.Destroy();
}

void SyncState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SyncState::Clear() {
// @@protoc_insertion_point(message_clear_start:ratelimit.SyncState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.client_id_.ClearToEmpty();
  _impl_.source_node_id_.ClearToEmpty();
  ::memset(&_impl_.tokens_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.last_refill_timestamp_) -
      reinterpret_cast<char*>(&_impl_.tokens_)) + sizeof(_impl_.last_refill_timestamp_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SyncState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string client_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_client_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ratelimit.SyncState.client_id"));
        } else
          goto handle_unusual;
        continue;
      // int64 tokens = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.tokens_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 last_refill_timestamp = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.last_refill_timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string source_node_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_source_node_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ratelimit.SyncState.source_node_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SyncState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ratelimit.SyncState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string client_id = 1;
  if (!this->_internal_client_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_client_id().data(), static_cast<int>(this->_internal_client_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ratelimit.SyncState.client_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_client_id(), target);
  }

  // int64 tokens = 2;
  if (this->_internal_tokens() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_tokens(), target);
  }

  // int64 last_refill_timestamp = 3;
  if (this->_internal_last_refill_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_last_refill_timestamp(), target);
  }

  // string source_node_id = 4;
  if (!this->_internal_source_node_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_source_node_id().data(), static_cast<int>(this->_internal_source_node_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ratelimit.SyncState.source_node_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_source_node_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ratelimit.SyncState)
  return target;
}

size_t SyncState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ratelimit.SyncState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string client_id = 1;
  if (!this->_internal_client_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_client_id());
  }

  // string source_node_id = 4;
  if (!this->_internal_source_node_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_source_node_id());
  }

  // int64 tokens = 2;
  if (this->_internal_tokens() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_tokens());
  }

  // int64 last_refill_timestamp = 3;
  if (this->_internal_last_refill_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_last_refill_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SyncState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SyncState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SyncState::GetClassData() const { return &_class_data_; }


void SyncState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SyncState*>(&to_msg);
  auto& from = static_cast<const SyncState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ratelimit.SyncState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_client_id().empty()) {
    _this->_internal_set_client_id(from._internal_client_id());
  }
  if (!from._internal_source_node_id().empty()) {
    _this->_internal_set_source_node_id(from._internal_source_node_id());
  }
  if (from._internal_tokens() != 0) {
    _this->_internal_set_tokens(from._internal_tokens());
  }
  if (from._internal_last_refill_timestamp() != 0) {
    _this->_internal_set_last_refill_timestamp(from._internal_last_refill_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SyncState::CopyFrom(const SyncState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ratelimit.SyncState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SyncState::IsInitialized() const {
  return true;
}

void SyncState::InternalSwap(SyncState* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.client_id_, lhs_arena,
      &other->_impl_.client_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.source_node_id_, lhs_arena,
      &other->_impl_.source_node_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SyncState, _impl_.last_refill_timestamp_)
      + sizeof(SyncState::_impl_.last_refill_timestamp_)
      - PROTOBUF_FIELD_OFFSET(SyncState, _impl_.tokens_)>(
          reinterpret_cast<char*>(&_impl_.tokens_),
          reinterpret_cast<char*>(&other->_impl_.tokens_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SyncState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fnode_2eproto_getter, &descriptor_table_proto_2fnode_2eproto_once,
      file_level_metadata_proto_2fnode_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ratelimit
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ratelimit::LimitState*
Arena::CreateMaybeMessage< ::ratelimit::LimitState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ratelimit::LimitState >(arena);
}
template<> PROTOBUF_NOINLINE ::ratelimit::LimitRequest*
Arena::CreateMaybeMessage< ::ratelimit::LimitRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ratelimit::LimitRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::ratelimit::LimitResponse*
Arena::CreateMaybeMessage< ::ratelimit::LimitResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ratelimit::LimitResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::ratelimit::SyncState*
Arena::CreateMaybeMessage< ::ratelimit::SyncState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ratelimit::SyncState >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
