// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node.proto

#include "node.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ratelimit {

inline constexpr SyncState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : client_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        source_node_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        tokens_{::int64_t{0}},
        last_refill_timestamp_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SyncState::SyncState(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SyncStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SyncStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SyncStateDefaultTypeInternal() {}
  union {
    SyncState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SyncStateDefaultTypeInternal _SyncState_default_instance_;

inline constexpr LimitResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : node_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        remaining_tokens_{::int64_t{0}},
        retry_after_ms_{::int64_t{0}},
        allowed_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LimitResponse::LimitResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LimitResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LimitResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LimitResponseDefaultTypeInternal() {}
  union {
    LimitResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LimitResponseDefaultTypeInternal _LimitResponse_default_instance_;

inline constexpr LimitRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : client_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        tokens_requested_{::int64_t{0}},
        timestamp_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LimitRequest::LimitRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LimitRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LimitRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LimitRequestDefaultTypeInternal() {}
  union {
    LimitRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LimitRequestDefaultTypeInternal _LimitRequest_default_instance_;
}  // namespace ratelimit
static ::_pb::Metadata file_level_metadata_node_2eproto[3];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_node_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_node_2eproto = nullptr;
const ::uint32_t TableStruct_node_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ratelimit::LimitRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ratelimit::LimitRequest, _impl_.client_id_),
    PROTOBUF_FIELD_OFFSET(::ratelimit::LimitRequest, _impl_.tokens_requested_),
    PROTOBUF_FIELD_OFFSET(::ratelimit::LimitRequest, _impl_.timestamp_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ratelimit::LimitResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ratelimit::LimitResponse, _impl_.allowed_),
    PROTOBUF_FIELD_OFFSET(::ratelimit::LimitResponse, _impl_.remaining_tokens_),
    PROTOBUF_FIELD_OFFSET(::ratelimit::LimitResponse, _impl_.retry_after_ms_),
    PROTOBUF_FIELD_OFFSET(::ratelimit::LimitResponse, _impl_.node_id_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::ratelimit::SyncState, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::ratelimit::SyncState, _impl_.client_id_),
    PROTOBUF_FIELD_OFFSET(::ratelimit::SyncState, _impl_.tokens_),
    PROTOBUF_FIELD_OFFSET(::ratelimit::SyncState, _impl_.last_refill_timestamp_),
    PROTOBUF_FIELD_OFFSET(::ratelimit::SyncState, _impl_.source_node_id_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ratelimit::LimitRequest)},
        {11, -1, -1, sizeof(::ratelimit::LimitResponse)},
        {23, -1, -1, sizeof(::ratelimit::SyncState)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::ratelimit::_LimitRequest_default_instance_._instance,
    &::ratelimit::_LimitResponse_default_instance_._instance,
    &::ratelimit::_SyncState_default_instance_._instance,
};
const char descriptor_table_protodef_node_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\nnode.proto\022\tratelimit\"N\n\014LimitRequest\022"
    "\021\n\tclient_id\030\001 \001(\t\022\030\n\020tokens_requested\030\002"
    " \001(\003\022\021\n\ttimestamp\030\003 \001(\003\"c\n\rLimitResponse"
    "\022\017\n\007allowed\030\001 \001(\010\022\030\n\020remaining_tokens\030\002 "
    "\001(\003\022\026\n\016retry_after_ms\030\003 \001(\003\022\017\n\007node_id\030\004"
    " \001(\t\"e\n\tSyncState\022\021\n\tclient_id\030\001 \001(\t\022\016\n\006"
    "tokens\030\002 \001(\003\022\035\n\025last_refill_timestamp\030\003 "
    "\001(\003\022\026\n\016source_node_id\030\004 \001(\t2\227\001\n\022RateLimi"
    "terService\022\?\n\nCheckLimit\022\027.ratelimit.Lim"
    "itRequest\032\030.ratelimit.LimitResponse\022@\n\016S"
    "yncTokenState\022\024.ratelimit.SyncState\032\030.ra"
    "telimit.LimitResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_node_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_node_2eproto = {
    false,
    false,
    469,
    descriptor_table_protodef_node_2eproto,
    "node.proto",
    &descriptor_table_node_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_node_2eproto::offsets,
    file_level_metadata_node_2eproto,
    file_level_enum_descriptors_node_2eproto,
    file_level_service_descriptors_node_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_node_2eproto_getter() {
  return &descriptor_table_node_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_node_2eproto(&descriptor_table_node_2eproto);
namespace ratelimit {
// ===================================================================

class LimitRequest::_Internal {
 public:
};

LimitRequest::LimitRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ratelimit.LimitRequest)
}
inline PROTOBUF_NDEBUG_INLINE LimitRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : client_id_(arena, from.client_id_),
        _cached_size_{0} {}

LimitRequest::LimitRequest(
    ::google::protobuf::Arena* arena,
    const LimitRequest& from)
    : ::google::protobuf::Message(arena) {
  LimitRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, tokens_requested_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, tokens_requested_),
           offsetof(Impl_, timestamp_) -
               offsetof(Impl_, tokens_requested_) +
               sizeof(Impl_::timestamp_));

  // @@protoc_insertion_point(copy_constructor:ratelimit.LimitRequest)
}
inline PROTOBUF_NDEBUG_INLINE LimitRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : client_id_(arena),
        _cached_size_{0} {}

inline void LimitRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, tokens_requested_),
           0,
           offsetof(Impl_, timestamp_) -
               offsetof(Impl_, tokens_requested_) +
               sizeof(Impl_::timestamp_));
}
LimitRequest::~LimitRequest() {
  // @@protoc_insertion_point(destructor:ratelimit.LimitRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LimitRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.client_id_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void LimitRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ratelimit.LimitRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.client_id_.ClearToEmpty();
  ::memset(&_impl_.tokens_requested_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.timestamp_) -
      reinterpret_cast<char*>(&_impl_.tokens_requested_)) + sizeof(_impl_.timestamp_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LimitRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 40, 2> LimitRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LimitRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string client_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(LimitRequest, _impl_.client_id_)}},
    // int64 tokens_requested = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LimitRequest, _impl_.tokens_requested_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(LimitRequest, _impl_.tokens_requested_)}},
    // int64 timestamp = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LimitRequest, _impl_.timestamp_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(LimitRequest, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string client_id = 1;
    {PROTOBUF_FIELD_OFFSET(LimitRequest, _impl_.client_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 tokens_requested = 2;
    {PROTOBUF_FIELD_OFFSET(LimitRequest, _impl_.tokens_requested_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 timestamp = 3;
    {PROTOBUF_FIELD_OFFSET(LimitRequest, _impl_.timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\26\11\0\0\0\0\0\0"
    "ratelimit.LimitRequest"
    "client_id"
  }},
};

::uint8_t* LimitRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ratelimit.LimitRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string client_id = 1;
  if (!this->_internal_client_id().empty()) {
    const std::string& _s = this->_internal_client_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ratelimit.LimitRequest.client_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int64 tokens_requested = 2;
  if (this->_internal_tokens_requested() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_tokens_requested(), target);
  }

  // int64 timestamp = 3;
  if (this->_internal_timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<3>(
            stream, this->_internal_timestamp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ratelimit.LimitRequest)
  return target;
}

::size_t LimitRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ratelimit.LimitRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string client_id = 1;
  if (!this->_internal_client_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_client_id());
  }

  // int64 tokens_requested = 2;
  if (this->_internal_tokens_requested() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_tokens_requested());
  }

  // int64 timestamp = 3;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData LimitRequest::_class_data_ = {
    LimitRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* LimitRequest::GetClassData() const {
  return &_class_data_;
}

void LimitRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<LimitRequest*>(&to_msg);
  auto& from = static_cast<const LimitRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ratelimit.LimitRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_client_id().empty()) {
    _this->_internal_set_client_id(from._internal_client_id());
  }
  if (from._internal_tokens_requested() != 0) {
    _this->_internal_set_tokens_requested(from._internal_tokens_requested());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LimitRequest::CopyFrom(const LimitRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ratelimit.LimitRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LimitRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* LimitRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void LimitRequest::InternalSwap(LimitRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.client_id_, &other->_impl_.client_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LimitRequest, _impl_.timestamp_)
      + sizeof(LimitRequest::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(LimitRequest, _impl_.tokens_requested_)>(
          reinterpret_cast<char*>(&_impl_.tokens_requested_),
          reinterpret_cast<char*>(&other->_impl_.tokens_requested_));
}

::google::protobuf::Metadata LimitRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_node_2eproto_getter, &descriptor_table_node_2eproto_once,
      file_level_metadata_node_2eproto[0]);
}
// ===================================================================

class LimitResponse::_Internal {
 public:
};

LimitResponse::LimitResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ratelimit.LimitResponse)
}
inline PROTOBUF_NDEBUG_INLINE LimitResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : node_id_(arena, from.node_id_),
        _cached_size_{0} {}

LimitResponse::LimitResponse(
    ::google::protobuf::Arena* arena,
    const LimitResponse& from)
    : ::google::protobuf::Message(arena) {
  LimitResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, remaining_tokens_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, remaining_tokens_),
           offsetof(Impl_, allowed_) -
               offsetof(Impl_, remaining_tokens_) +
               sizeof(Impl_::allowed_));

  // @@protoc_insertion_point(copy_constructor:ratelimit.LimitResponse)
}
inline PROTOBUF_NDEBUG_INLINE LimitResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : node_id_(arena),
        _cached_size_{0} {}

inline void LimitResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, remaining_tokens_),
           0,
           offsetof(Impl_, allowed_) -
               offsetof(Impl_, remaining_tokens_) +
               sizeof(Impl_::allowed_));
}
LimitResponse::~LimitResponse() {
  // @@protoc_insertion_point(destructor:ratelimit.LimitResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LimitResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.node_id_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void LimitResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ratelimit.LimitResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.node_id_.ClearToEmpty();
  ::memset(&_impl_.remaining_tokens_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.allowed_) -
      reinterpret_cast<char*>(&_impl_.remaining_tokens_)) + sizeof(_impl_.allowed_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LimitResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 39, 2> LimitResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LimitResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string node_id = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(LimitResponse, _impl_.node_id_)}},
    // bool allowed = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(LimitResponse, _impl_.allowed_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LimitResponse, _impl_.allowed_)}},
    // int64 remaining_tokens = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LimitResponse, _impl_.remaining_tokens_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(LimitResponse, _impl_.remaining_tokens_)}},
    // int64 retry_after_ms = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(LimitResponse, _impl_.retry_after_ms_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(LimitResponse, _impl_.retry_after_ms_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool allowed = 1;
    {PROTOBUF_FIELD_OFFSET(LimitResponse, _impl_.allowed_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // int64 remaining_tokens = 2;
    {PROTOBUF_FIELD_OFFSET(LimitResponse, _impl_.remaining_tokens_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 retry_after_ms = 3;
    {PROTOBUF_FIELD_OFFSET(LimitResponse, _impl_.retry_after_ms_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string node_id = 4;
    {PROTOBUF_FIELD_OFFSET(LimitResponse, _impl_.node_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\0\0\0\7\0\0\0"
    "ratelimit.LimitResponse"
    "node_id"
  }},
};

::uint8_t* LimitResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ratelimit.LimitResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool allowed = 1;
  if (this->_internal_allowed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_allowed(), target);
  }

  // int64 remaining_tokens = 2;
  if (this->_internal_remaining_tokens() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_remaining_tokens(), target);
  }

  // int64 retry_after_ms = 3;
  if (this->_internal_retry_after_ms() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<3>(
            stream, this->_internal_retry_after_ms(), target);
  }

  // string node_id = 4;
  if (!this->_internal_node_id().empty()) {
    const std::string& _s = this->_internal_node_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ratelimit.LimitResponse.node_id");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ratelimit.LimitResponse)
  return target;
}

::size_t LimitResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ratelimit.LimitResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string node_id = 4;
  if (!this->_internal_node_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_node_id());
  }

  // int64 remaining_tokens = 2;
  if (this->_internal_remaining_tokens() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_remaining_tokens());
  }

  // int64 retry_after_ms = 3;
  if (this->_internal_retry_after_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_retry_after_ms());
  }

  // bool allowed = 1;
  if (this->_internal_allowed() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData LimitResponse::_class_data_ = {
    LimitResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* LimitResponse::GetClassData() const {
  return &_class_data_;
}

void LimitResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<LimitResponse*>(&to_msg);
  auto& from = static_cast<const LimitResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ratelimit.LimitResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_node_id().empty()) {
    _this->_internal_set_node_id(from._internal_node_id());
  }
  if (from._internal_remaining_tokens() != 0) {
    _this->_internal_set_remaining_tokens(from._internal_remaining_tokens());
  }
  if (from._internal_retry_after_ms() != 0) {
    _this->_internal_set_retry_after_ms(from._internal_retry_after_ms());
  }
  if (from._internal_allowed() != 0) {
    _this->_internal_set_allowed(from._internal_allowed());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LimitResponse::CopyFrom(const LimitResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ratelimit.LimitResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LimitResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* LimitResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void LimitResponse::InternalSwap(LimitResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.node_id_, &other->_impl_.node_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LimitResponse, _impl_.allowed_)
      + sizeof(LimitResponse::_impl_.allowed_)
      - PROTOBUF_FIELD_OFFSET(LimitResponse, _impl_.remaining_tokens_)>(
          reinterpret_cast<char*>(&_impl_.remaining_tokens_),
          reinterpret_cast<char*>(&other->_impl_.remaining_tokens_));
}

::google::protobuf::Metadata LimitResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_node_2eproto_getter, &descriptor_table_node_2eproto_once,
      file_level_metadata_node_2eproto[1]);
}
// ===================================================================

class SyncState::_Internal {
 public:
};

SyncState::SyncState(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ratelimit.SyncState)
}
inline PROTOBUF_NDEBUG_INLINE SyncState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : client_id_(arena, from.client_id_),
        source_node_id_(arena, from.source_node_id_),
        _cached_size_{0} {}

SyncState::SyncState(
    ::google::protobuf::Arena* arena,
    const SyncState& from)
    : ::google::protobuf::Message(arena) {
  SyncState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, tokens_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, tokens_),
           offsetof(Impl_, last_refill_timestamp_) -
               offsetof(Impl_, tokens_) +
               sizeof(Impl_::last_refill_timestamp_));

  // @@protoc_insertion_point(copy_constructor:ratelimit.SyncState)
}
inline PROTOBUF_NDEBUG_INLINE SyncState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : client_id_(arena),
        source_node_id_(arena),
        _cached_size_{0} {}

inline void SyncState::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, tokens_),
           0,
           offsetof(Impl_, last_refill_timestamp_) -
               offsetof(Impl_, tokens_) +
               sizeof(Impl_::last_refill_timestamp_));
}
SyncState::~SyncState() {
  // @@protoc_insertion_point(destructor:ratelimit.SyncState)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SyncState::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.client_id_.Destroy();
  _impl_.source_node_id_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void SyncState::Clear() {
// @@protoc_insertion_point(message_clear_start:ratelimit.SyncState)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.client_id_.ClearToEmpty();
  _impl_.source_node_id_.ClearToEmpty();
  ::memset(&_impl_.tokens_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.last_refill_timestamp_) -
      reinterpret_cast<char*>(&_impl_.tokens_)) + sizeof(_impl_.last_refill_timestamp_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* SyncState::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 51, 2> SyncState::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SyncState_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string source_node_id = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(SyncState, _impl_.source_node_id_)}},
    // string client_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SyncState, _impl_.client_id_)}},
    // int64 tokens = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SyncState, _impl_.tokens_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(SyncState, _impl_.tokens_)}},
    // int64 last_refill_timestamp = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SyncState, _impl_.last_refill_timestamp_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(SyncState, _impl_.last_refill_timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string client_id = 1;
    {PROTOBUF_FIELD_OFFSET(SyncState, _impl_.client_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 tokens = 2;
    {PROTOBUF_FIELD_OFFSET(SyncState, _impl_.tokens_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 last_refill_timestamp = 3;
    {PROTOBUF_FIELD_OFFSET(SyncState, _impl_.last_refill_timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string source_node_id = 4;
    {PROTOBUF_FIELD_OFFSET(SyncState, _impl_.source_node_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\11\0\0\16\0\0\0"
    "ratelimit.SyncState"
    "client_id"
    "source_node_id"
  }},
};

::uint8_t* SyncState::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ratelimit.SyncState)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string client_id = 1;
  if (!this->_internal_client_id().empty()) {
    const std::string& _s = this->_internal_client_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ratelimit.SyncState.client_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int64 tokens = 2;
  if (this->_internal_tokens() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_tokens(), target);
  }

  // int64 last_refill_timestamp = 3;
  if (this->_internal_last_refill_timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<3>(
            stream, this->_internal_last_refill_timestamp(), target);
  }

  // string source_node_id = 4;
  if (!this->_internal_source_node_id().empty()) {
    const std::string& _s = this->_internal_source_node_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ratelimit.SyncState.source_node_id");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ratelimit.SyncState)
  return target;
}

::size_t SyncState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ratelimit.SyncState)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string client_id = 1;
  if (!this->_internal_client_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_client_id());
  }

  // string source_node_id = 4;
  if (!this->_internal_source_node_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_source_node_id());
  }

  // int64 tokens = 2;
  if (this->_internal_tokens() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_tokens());
  }

  // int64 last_refill_timestamp = 3;
  if (this->_internal_last_refill_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_last_refill_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData SyncState::_class_data_ = {
    SyncState::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* SyncState::GetClassData() const {
  return &_class_data_;
}

void SyncState::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<SyncState*>(&to_msg);
  auto& from = static_cast<const SyncState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ratelimit.SyncState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_client_id().empty()) {
    _this->_internal_set_client_id(from._internal_client_id());
  }
  if (!from._internal_source_node_id().empty()) {
    _this->_internal_set_source_node_id(from._internal_source_node_id());
  }
  if (from._internal_tokens() != 0) {
    _this->_internal_set_tokens(from._internal_tokens());
  }
  if (from._internal_last_refill_timestamp() != 0) {
    _this->_internal_set_last_refill_timestamp(from._internal_last_refill_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SyncState::CopyFrom(const SyncState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ratelimit.SyncState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SyncState::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* SyncState::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void SyncState::InternalSwap(SyncState* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.client_id_, &other->_impl_.client_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.source_node_id_, &other->_impl_.source_node_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SyncState, _impl_.last_refill_timestamp_)
      + sizeof(SyncState::_impl_.last_refill_timestamp_)
      - PROTOBUF_FIELD_OFFSET(SyncState, _impl_.tokens_)>(
          reinterpret_cast<char*>(&_impl_.tokens_),
          reinterpret_cast<char*>(&other->_impl_.tokens_));
}

::google::protobuf::Metadata SyncState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_node_2eproto_getter, &descriptor_table_node_2eproto_once,
      file_level_metadata_node_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ratelimit
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
